openapi: 3.0.3
info:
  title: Productive.io API – Attachments
  version: 2.0.0
paths:
  /api/v2/attachments:
    get:
      summary: Get attachments GET
      operationId: getAttachments
      tags:
      - Attachments
      parameters:
      - name: filter[comment_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by comment_id (array)
      - name: filter[page_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by page_id (array)
      - name: filter[task_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by task_id (array)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a attachment POST
      operationId: postAttachments
      tags:
      - Attachments
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/attachments/{id}:
    get:
      summary: Gets a attachment GET
      operationId: getAttachmentsId
      tags:
      - Attachments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a attachment PATCH
      operationId: patchAttachmentsId
      tags:
      - Attachments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a attachment DELETE
      operationId: deleteAttachmentsId
      tags:
      - Attachments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
