openapi: 3.0.3
info:
  title: Productive.io API – Companies
  version: 2.0.0
paths:
  /api/v2/companies:
    get:
      summary: Get companies GET
      operationId: getCompanies
      tags:
      - Companies
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by id (integer)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by company_id (integer)
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by name (string)
      - name: filter[company_code]
        in: query
        required: false
        schema:
          type: string
        description: Filter by company_code (string)
      - name: filter[billing_name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by billing_name (string)
      - name: filter[default_currency]
        in: query
        required: false
        schema:
          type: string
        description: Filter by default_currency (string)
      - name: filter[default_subsidiary_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by default_subsidiary_id (string)
      - name: filter[subsidiary_id]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by subsidiary_id (integer)
      - name: filter[default_tax_rate_id]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by default_tax_rate_id (integer)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by project_id (integer)
      - name: filter[vat]
        in: query
        required: false
        schema:
          type: string
        description: Filter by vat (string)
      - name: filter[status]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by status (integer)
      - name: filter[1]
        in: query
        required: false
        schema:
          type: string
        description: Filter by 1 (Active)
      - name: filter[2]
        in: query
        required: false
        schema:
          type: string
        description: Filter by 2 (Archived)
      - name: filter[tags]
        in: query
        required: false
        schema:
          type: string
        description: Filter by tags (string)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by created_at (date)
      - name: filter[archived_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by archived_at (date)
      - name: filter[last_activity_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by last_activity_at (date)
      - name: filter[due_days]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by due_days (integer)
      - name: filter[payment_terms]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by payment_terms (integer)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a company POST
      operationId: postCompanies
      tags:
      - Companies
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/companies/{id}:
    get:
      summary: Gets a company GET
      operationId: getCompaniesId
      tags:
      - Companies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a company PATCH
      operationId: patchCompaniesId
      tags:
      - Companies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/companies/{id}/archive:
    patch:
      summary: Archives a company PATCH
      operationId: patchCompaniesIdArchive
      tags:
      - Companies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/companies/{id}/restore:
    patch:
      summary: Restores a company PATCH
      operationId: patchCompaniesIdRestore
      tags:
      - Companies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
