openapi: 3.0.3
info:
  title: Productive.io API – Deals
  version: 2.0.0
paths:
  /api/v2/deals:
    get:
      summary: Get deals GET
      operationId: getDeals
      tags:
      - Deals
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[number]
        in: query
        required: false
        schema:
          type: string
        description: Filter by number (string)
      - name: filter[responsible_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by responsible_id (array)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by creator_id (array)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[status_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by status_id (array)
      - name: filter[stage_status_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by stage_status_id (array)
      - name: filter[contract_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by contract_id (array)
      - name: filter[recurring]
        in: query
        required: false
        schema:
          type: string
        description: Filter by recurring (string)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[tags]
        in: query
        required: false
        schema:
          type: string
        description: Filter by tags (string)
      - name: filter[query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by query (string)
      - name: filter[won_date]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by won_date (automatically set date when won or overridden
          manually)
      - name: filter[lost_date]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by lost_date (automatically set date when lost or overridden
          manually)
      - name: filter[won_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by won_at (automatically set date when won)
      - name: filter[lost_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by lost_at (automatically set date when lost)
      - name: filter[needs_invoicing]
        in: query
        required: false
        schema:
          type: string
        description: Filter by needs_invoicing (string)
      - name: filter[type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by type (1: deal, 2: budget)'
      - name: filter[deal_type_id]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by deal_type_id (1: internal, 2: client)'
      - name: filter[project_type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by project_type (1: internal project, 2: client project)'
      - name: filter[budget_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by budget_status (1: open, 2: closed)'
      - name: filter[subsidiary_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by subsidiary_id (array)
      - name: filter[pipeline_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by pipeline_id (array)
      - name: filter[custom_fields]
        in: query
        required: false
        schema:
          type: string
        description: Filter by custom_fields (string)
      - name: filter[time_approval]
        in: query
        required: false
        schema:
          type: boolean
        description: Filter by time_approval (boolean)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - billable_time
          - budget_total
          - budget_used
          - budget_warning
          - budgeted_time
          - client_access
          - closed_at
          - company.name
          - cost
          - created_at
          - date
          - deal_status
          - end_date
          - estimated_time
          - expense
          - invoiced
          - last_activity_at
          - name
          - number
          - pending_invoicing
          - probability
          - profit
          - profit_margin
          - project.name
          - purchase_order_number
          - responsible.name
          - creator.name
          - revenue
          - stage_status
          - services_revenue
          - suffix
          - time_approval
          - total_budgeted_time
          - worked_time
          - -billable_time
          - -budget_total
          - -budget_used
          - -budget_warning
          - -budgeted_time
          - -client_access
          - -closed_at
          - -company.name
          - -cost
          - -created_at
          - -date
          - -deal_status
          - -end_date
          - -estimated_time
          - -expense
          - -invoiced
          - -last_activity_at
          - -name
          - -number
          - -pending_invoicing
          - -probability
          - -profit
          - -profit_margin
          - -project.name
          - -purchase_order_number
          - -responsible.name
          - -creator.name
          - -revenue
          - -stage_status
          - -services_revenue
          - -suffix
          - -time_approval
          - -total_budgeted_time
          - -worked_time
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a deal POST
      operationId: postDeals
      tags:
      - Deals
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/deals/{id}:
    get:
      summary: Gets a deal GET
      operationId: getDealsId
      tags:
      - Deals
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a deal PATCH
      operationId: patchDealsId
      tags:
      - Deals
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a deal DELETE
      operationId: deleteDealsId
      tags:
      - Deals
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/deals/create_from_origin:
    post:
      summary: Creates a budget from origin deal POST
      operationId: postDealsCreateFromOrigin
      tags:
      - Deals
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/deals/copy:
    post:
      summary: Copies a deal POST
      operationId: postDealsCopy
      tags:
      - Deals
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/deals/{id}/open:
    patch:
      summary: Opens a deal PATCH
      operationId: patchDealsIdOpen
      tags:
      - Deals
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/deals/{id}/close:
    patch:
      summary: Closes a deal PATCH
      operationId: patchDealsIdClose
      tags:
      - Deals
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
