openapi: 3.0.3
info:
  title: Productive.io API – Deleted Items
  version: 2.0.0
paths:
  /api/v2/deleted_items:
    get:
      summary: Get deleted items GET
      operationId: getDeletedItems
      tags:
      - Deleted Items
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[item_type]
        in: query
        required: false
        schema:
          type: string
        description: Filter by item_type (string)
      - name: filter[deleter_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by deleter_id (string)
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by name (string)
      - name: filter[location]
        in: query
        required: false
        schema:
          type: string
        description: Filter by location (string)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by created_at (date)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/deleted_items/{id}:
    get:
      summary: Gets a deleted item GET
      operationId: getDeletedItemsId
      tags:
      - Deleted Items
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/deleted_items/{id}/restore:
    patch:
      summary: Restores deleted object PATCH
      operationId: patchDeletedItemsIdRestore
      tags:
      - Deleted Items
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
