openapi: 3.0.3
info:
  title: Productive.io API – Expenses   Bulk
  version: 2.0.0
paths:
  /api/v2/expenses:
    patch:
      summary: Update expenses PATCH
      operationId: patchExpenses
      tags:
      - Expenses   Bulk
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Delete expenses DELETE
      operationId: deleteExpenses
      tags:
      - Expenses   Bulk
      parameters: []
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
