openapi: 3.0.3
info:
  title: Productive.io API – Expenses
  version: 2.0.0
paths:
  /api/v2/expenses:
    get:
      summary: Get expenses GET
      operationId: getExpenses
      tags:
      - Expenses
      parameters:
      - name: filter[service_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by service_id (array)
      - name: filter[quote_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by quote_id (array)
      - name: filter[person_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by person_id (array)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by creator_id (string)
      - name: filter[vendor_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by vendor_id (array)
      - name: filter[approver_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by approver_id (array)
      - name: filter[purchase_order_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by purchase_order_id (string)
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by name (string)
      - name: filter[reimbursable]
        in: query
        required: false
        schema:
          type: string
        description: Filter by reimbursable (string)
      - name: filter[service_type_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by service_type_id (array)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[invoice_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by invoice_id (array)
      - name: filter[responsible_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by responsible_id (array)
      - name: filter[date_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by date_after (string)
      - name: filter[date_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by date_before (string)
      - name: filter[pay_on_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by pay_on_after (string)
      - name: filter[pay_on_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by pay_on_before (string)
      - name: filter[paid_on_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by paid_on_after (string)
      - name: filter[paid_on_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by paid_on_before (string)
      - name: filter[status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by status (1: paid, 2: unpaid)'
      - name: filter[invoiced]
        in: query
        required: false
        schema:
          type: string
        description: Filter by invoiced (string)
      - name: filter[invoicing_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoicing_status (1: not invoiced, 2: drafted, 3:
          finalized)'
      - name: filter[section_name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by section_name (string)
      - name: filter[query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by query (string)
      - name: filter[approval_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by approval_status (1: approved, 2: not approved, 3:
          rejected, 4: auto approved)'
      - name: filter[reimbursement]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by reimbursement (1: not reimbursable, 2: needs reimbursing,
          3: reimbursed)'
      - name: filter[export_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by export_status (1: exported, 2: not exported)'
      - name: filter[date]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by date (date)
      - name: filter[pay_on]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by pay_on (date)
      - name: filter[paid_on]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by paid_on (date)
      - name: filter[reimbursed_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by reimbursed_on (string)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by created_at (date)
      - name: filter[amount]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount (money)
      - name: filter[billable_amount]
        in: query
        required: false
        schema:
          type: string
        description: Filter by billable_amount (money)
      - name: filter[recognized_revenue]
        in: query
        required: false
        schema:
          type: string
        description: Filter by recognized_revenue (money)
      - name: filter[profit]
        in: query
        required: false
        schema:
          type: string
        description: Filter by profit (string)
      - name: filter[jump_query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by jump_query (string)
      - name: filter[full_query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by full_query (string)
      - name: filter[fuzzy_people]
        in: query
        required: false
        schema:
          type: string
        description: Filter by fuzzy_people (string)
      - name: filter[fuzzy_dates]
        in: query
        required: false
        schema:
          type: string
        description: Filter by fuzzy_dates (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - name
          - date
          - pay_on
          - paid_on
          - amount
          - billable_amount
          - profit
          - deal.company.name
          - deal.project.name
          - deal.name
          - service_type.name
          - invoicing_status
          - -name
          - -date
          - -pay_on
          - -paid_on
          - -amount
          - -billable_amount
          - -profit
          - -deal.company.name
          - -deal.project.name
          - -deal.name
          - -service_type.name
          - -invoicing_status
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a expense POST
      operationId: postExpenses
      tags:
      - Expenses
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/expenses/{id}:
    get:
      summary: Gets a expense GET
      operationId: getExpensesId
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a expense PATCH
      operationId: patchExpensesId
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a expense DELETE
      operationId: deleteExpensesId
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/expenses/copy:
    post:
      summary: Copy an expense POST
      operationId: postExpensesCopy
      tags:
      - Expenses
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/expenses/{id}/approve:
    patch:
      summary: Approves an expense PATCH
      operationId: patchExpensesIdApprove
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/expenses/{id}/unapprove:
    patch:
      summary: Unapproves an expense PATCH
      operationId: patchExpensesIdUnapprove
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/expenses/{id}/export:
    patch:
      summary: Exports an expense PATCH
      operationId: patchExpensesIdExport
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/expenses/{id}/export_update:
    patch:
      summary: Updates exported expense PATCH
      operationId: patchExpensesIdExportUpdate
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
