openapi: 3.0.3
info:
  title: Productive.io API – Invoices
  version: 2.0.0
paths:
  /api/v2/invoices:
    get:
      summary: Get invoices GET
      operationId: getInvoices
      tags:
      - Invoices
      parameters:
      - name: filter[amount]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount (string)
      - name: filter[amount_credited]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_credited (string)
      - name: filter[amount_credited_with_tax]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_credited_with_tax (string)
      - name: filter[amount_paid]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_paid (string)
      - name: filter[amount_tax]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_tax (string)
      - name: filter[amount_unpaid]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_unpaid (string)
      - name: filter[amount_with_tax]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_with_tax (string)
      - name: filter[amount_written_off]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_written_off (string)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by created_at (string)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by creator_id (array)
      - name: filter[credited]
        in: query
        required: false
        schema:
          type: string
        description: Filter by credited (string)
      - name: filter[currency]
        in: query
        required: false
        schema:
          type: string
        description: Filter by currency (string)
      - name: filter[deal_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by deal_id (array)
      - name: filter[delivery_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by delivery_on (string)
      - name: filter[export_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by export_status (1: exported, 2: unexported)'
      - name: filter[full_query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by full_query (string)
      - name: filter[fuzzy_dates]
        in: query
        required: false
        schema:
          type: string
        description: Filter by fuzzy_dates (string)
      - name: filter[fuzzy_people]
        in: query
        required: false
        schema:
          type: string
        description: Filter by fuzzy_people (string)
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[invoice_aging]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoice_aging (0: other, 1: overdue < 15 days, 2:
          overdue 15 - 45 days, 3: overdue 45+ days, 4: not overdue)'
      - name: filter[invoice_state]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoice_state (1: draft, 2: finalized)'
      - name: filter[invoice_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoice_status (0: unsent, 1: paid, 2: overdue, 3:
          not_overdue, 4: draft)'
      - name: filter[invoice_type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoice_type (1: invoice, 2: credit note)'
      - name: filter[invoiced_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by invoiced_on (string)
      - name: filter[invoicing_method]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoicing_method (1: actuals, 2: uninvoiced amount,
          3: percentage)'
      - name: filter[issuer_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by issuer_id (array)
      - name: filter[jump_query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by jump_query (string)
      - name: filter[last_activity_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by last_activity_at (string)
      - name: filter[number]
        in: query
        required: false
        schema:
          type: string
        description: Filter by number (string)
      - name: filter[overdue_status]
        in: query
        required: false
        schema:
          type: string
        description: Filter by overdue_status (string)
      - name: filter[paid_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by paid_on (string)
      - name: filter[parent_invoice_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by parent_invoice_id (array)
      - name: filter[pay_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by pay_on (string)
      - name: filter[payment_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by payment_status (1: paid, 2: unpaid, 3: partially paid)'
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[purchase_order_number]
        in: query
        required: false
        schema:
          type: string
        description: Filter by purchase_order_number (string)
      - name: filter[query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by query (string)
      - name: filter[responsible_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by responsible_id (array)
      - name: filter[sent_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by sent_on (string)
      - name: filter[sent_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by sent_status (1: sent, 2: unsent)'
      - name: filter[status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by status (0: unsent, 1: paid, 2: overdue, 3: not_overdue,
          4: draft)'
      - name: filter[subscriber_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by subscriber_id (array)
      - name: filter[subsidiary_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by subsidiary_id (array)
      - name: filter[tags]
        in: query
        required: false
        schema:
          type: string
        description: Filter by tags (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - amount
          - amount_credited
          - amount_credited_with_tax
          - amount_paid
          - amount_tax
          - amount_with_tax
          - amount_written_off
          - company_name
          - created_at
          - credited
          - custom_fields
          - deleted_at
          - delivery_on
          - discount
          - invoiced_on
          - last_activity_at
          - number
          - pay_on
          - purchase_order_number
          - sent_on
          - -amount
          - -amount_credited
          - -amount_credited_with_tax
          - -amount_paid
          - -amount_tax
          - -amount_with_tax
          - -amount_written_off
          - -company_name
          - -created_at
          - -credited
          - -custom_fields
          - -deleted_at
          - -delivery_on
          - -discount
          - -invoiced_on
          - -last_activity_at
          - -number
          - -pay_on
          - -purchase_order_number
          - -sent_on
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create an invoice POST
      operationId: postInvoices
      tags:
      - Invoices
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/invoices/{id}:
    get:
      summary: Gets an invoice GET
      operationId: getInvoicesId
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update an invoice PATCH
      operationId: patchInvoicesId
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes an invoice DELETE
      operationId: deleteInvoicesId
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/invoices/{id}/export:
    patch:
      summary: Exports an invoice PATCH
      operationId: patchInvoicesIdExport
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/invoices/{id}/export_update:
    patch:
      summary: Updates an exported invoice PATCH
      operationId: patchInvoicesIdExportUpdate
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/invoices/{id}/send:
    patch:
      summary: Sends an invoice PATCH
      operationId: patchInvoicesIdSend
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/invoices/{id}/finalize:
    patch:
      summary: Finalizes an invoice PATCH
      operationId: patchInvoicesIdFinalize
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/invoices/{id}/preview:
    get:
      summary: Preview invoice GET
      operationId: getInvoicesIdPreview
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
