openapi: 3.0.3
info:
  title: Productive.io API – Memberships
  version: 2.0.0
paths:
  /api/v2/memberships:
    get:
      summary: Get memberships GET
      operationId: getMemberships
      tags:
      - Memberships
      parameters:
      - name: filter[access_type_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by access_type_id (string)
      - name: filter[dashboard_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by dashboard_id (string)
      - name: filter[deal_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by deal_id (string)
      - name: filter[dynamic_group_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by dynamic_group_id (string)
      - name: filter[filter_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by filter_id (string)
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[page_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by page_id (string)
      - name: filter[person_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by person_id (string)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by project_id (string)
      - name: filter[target_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by target_id (string)
      - name: filter[target_type]
        in: query
        required: false
        schema:
          type: string
        description: Filter by target_type (string)
      - name: filter[type_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by type_id (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a membership POST
      operationId: postMemberships
      tags:
      - Memberships
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/memberships/{id}:
    get:
      summary: Gets a membership GET
      operationId: getMembershipsId
      tags:
      - Memberships
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    delete:
      summary: Deletes a membership DELETE
      operationId: deleteMembershipsId
      tags:
      - Memberships
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/memberships/:
    patch:
      summary: Update a membership PATCH
      operationId: patchMemberships
      tags:
      - Memberships
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
