openapi: 3.0.3
info:
  title: Productive.io API – Notifications
  version: 2.0.0
paths:
  /api/v2/notifications:
    get:
      summary: Get notifications GET
      operationId: getNotifications
      tags:
      - Notifications
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by before (string)
      - name: filter[after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by after (string)
      - name: filter[dismissed]
        in: query
        required: false
        schema:
          type: string
        description: Filter by dismissed (string)
      - name: filter[important]
        in: query
        required: false
        schema:
          type: string
        description: Filter by important (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/notifications/{id}:
    get:
      summary: Shows a notification GET
      operationId: getNotificationsId
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/notifications/{id}/dismiss:
    patch:
      summary: Dismisses a notification PATCH
      operationId: patchNotificationsIdDismiss
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/notifications/{id}/read:
    patch:
      summary: Reads a notification PATCH
      operationId: patchNotificationsIdRead
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/notifications/{id}/undismiss:
    patch:
      summary: Undismisses a notification PATCH
      operationId: patchNotificationsIdUndismiss
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
