openapi: 3.0.3
info:
  title: Productive.io API – Payments
  version: 2.0.0
paths:
  /api/v2/payments:
    get:
      summary: Get payments GET
      operationId: getPayments
      tags:
      - Payments
      parameters:
      - name: filter[invoice_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by invoice_id (array)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[budget_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by budget_id (string)
      - name: filter[paid_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by paid_after (string)
      - name: filter[paid_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by paid_before (string)
      - name: filter[subsidiary_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by subsidiary_id (array)
      - name: filter[paid_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by paid_on (string)
      - name: filter[number]
        in: query
        required: false
        schema:
          type: string
        description: Filter by number (string)
      - name: filter[written_off_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by written_off_on (string)
      - name: filter[external_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by external_id (string)
      - name: filter[amount]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - amount
          - paid_on
          - written_off_on
          - note
          - invoice.deal.company.name
          - invoice.deal.project.name
          - invoice.deal.name
          - invoice.number
          - date
          - -amount
          - -paid_on
          - -written_off_on
          - -note
          - -invoice.deal.company.name
          - -invoice.deal.project.name
          - -invoice.deal.name
          - -invoice.number
          - -date
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a payment POST
      operationId: postPayments
      tags:
      - Payments
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/payments/{id}:
    get:
      summary: Gets a payment GET
      operationId: getPaymentsId
      tags:
      - Payments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a payment PATCH
      operationId: patchPaymentsId
      tags:
      - Payments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a payment DELETE
      operationId: deletePaymentsId
      tags:
      - Payments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
