openapi: 3.0.3
info:
  title: Productive.io API – Prices
  version: 2.0.0
paths:
  /api/v2/prices:
    get:
      summary: Get prices GET
      operationId: getPrices
      tags:
      - Prices
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[service_type_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by service_type_id (array)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[rate_card_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by rate_card_id (array)
      - name: filter[time_tracking_enabled]
        in: query
        required: false
        schema:
          type: string
        description: Filter by time_tracking_enabled (string)
      - name: filter[booking_tracking_enabled]
        in: query
        required: false
        schema:
          type: string
        description: Filter by booking_tracking_enabled (string)
      - name: filter[expense_tracking_enabled]
        in: query
        required: false
        schema:
          type: string
        description: Filter by expense_tracking_enabled (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a price POST
      operationId: postPrices
      tags:
      - Prices
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/prices/{id}:
    get:
      summary: Gets a price GET
      operationId: getPricesId
      tags:
      - Prices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a price PATCH
      operationId: patchPricesId
      tags:
      - Prices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a price DELETE
      operationId: deletePricesId
      tags:
      - Prices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
