openapi: 3.0.3
info:
  title: Productive.io API – Revenue Distributions
  version: 2.0.0
paths:
  /api/v2/revenue_distributions:
    get:
      summary: Get revenue distributions GET
      operationId: getRevenueDistributions
      tags:
      - Revenue Distributions
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by id (array)
      - name: filter[deal_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by deal_id (array)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by creator_id (array)
      - name: filter[start_on]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by start_on (date)
      - name: filter[end_on]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by end_on (date)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by created_at (date)
      - name: filter[amount_percent]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount_percent (number)
      - name: filter[amount]
        in: query
        required: false
        schema:
          type: string
        description: Filter by amount (number)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - id
          - deal (name string)
          - deal_id
          - start_on
          - end_on
          - created_at
          - amount_percent
          - amount
          - -id
          - -deal (name string)
          - -deal_id
          - -start_on
          - -end_on
          - -created_at
          - -amount_percent
          - -amount
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a revenue distribution POST
      operationId: postRevenueDistributions
      tags:
      - Revenue Distributions
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/revenue_distributions/{id}:
    get:
      summary: Gets a revenue distribution GET
      operationId: getRevenueDistributionsId
      tags:
      - Revenue Distributions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    delete:
      summary: Deletes a revenue distribution DELETE
      operationId: deleteRevenueDistributionsId
      tags:
      - Revenue Distributions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/revenue_distributions/:
    patch:
      summary: Update a revenue distribution PATCH
      operationId: patchRevenueDistributions
      tags:
      - Revenue Distributions
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
