openapi: 3.0.3
info:
  title: Productive.io API – Services
  version: 2.0.0
paths:
  /api/v2/services:
    get:
      summary: Get services GET
      operationId: getServices
      tags:
      - Services
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[deal_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by deal_id (array)
      - name: filter[after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by after (string)
      - name: filter[before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by before (string)
      - name: filter[budget_date]
        in: query
        required: false
        schema:
          type: string
        description: Filter by budget_date (string)
      - name: filter[bookable_date]
        in: query
        required: false
        schema:
          type: string
        description: Filter by bookable_date (string)
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by name (string)
      - name: filter[task_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by task_id (array)
      - name: filter[person_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by person_id (array)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[budget_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by budget_status (1: open, 2: delivered)'
      - name: filter[unit]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by unit (1: hour, 2: piece, 3: day)'
      - name: filter[billing_type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by billing_type (1: fixed, 2: actuals, 3: none)'
      - name: filter[time_tracking_enabled]
        in: query
        required: false
        schema:
          type: boolean
        description: Filter by time_tracking_enabled (boolean)
      - name: filter[expense_tracking_enabled]
        in: query
        required: false
        schema:
          type: boolean
        description: Filter by expense_tracking_enabled (boolean)
      - name: filter[budget]
        in: query
        required: false
        schema:
          type: string
        description: Filter by budget (string)
      - name: filter[stage_status_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by stage_status_id (array)
      - name: filter[trackable_by_person_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by trackable_by_person_id (Filters services that both
          person sending the request and person passed to the filter can track on.)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a service POST
      operationId: postServices
      tags:
      - Services
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/services/{id}:
    get:
      summary: Gets a service GET
      operationId: getServicesId
      tags:
      - Services
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a service PATCH
      operationId: patchServicesId
      tags:
      - Services
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a service DELETE
      operationId: deleteServicesId
      tags:
      - Services
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
