openapi: 3.0.3
info:
  title: Productive.io API – Survey Field Options
  version: 2.0.0
paths:
  /api/v2/survey_field_options:
    get:
      summary: Get survey field options GET
      operationId: getSurveyFieldOptions
      tags:
      - Survey Field Options
      parameters:
      - name: filter[survey_field_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by survey_field_id (string)
      - name: filter[archived]
        in: query
        required: false
        schema:
          type: string
        description: "Filter by archived (â\x80\x98trueâ\x80\x99 or â\x80\x98falseâ\x80\
          \x99)"
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Creates a survey field option POST
      operationId: postSurveyFieldOptions
      tags:
      - Survey Field Options
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/survey_field_options/{id}:
    get:
      summary: Gets a survey field option GET
      operationId: getSurveyFieldOptionsId
      tags:
      - Survey Field Options
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Updates a survey field option PATCH
      operationId: patchSurveyFieldOptionsId
      tags:
      - Survey Field Options
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/survey_field_options/{id}/archive:
    patch:
      summary: Archives a survey field option PATCH
      operationId: patchSurveyFieldOptionsIdArchive
      tags:
      - Survey Field Options
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
