openapi: 3.0.3
info:
  title: Productive.io API – Survey Fields
  version: 2.0.0
paths:
  /api/v2/survey_fields:
    get:
      summary: Get survey fields GET
      operationId: getSurveyFields
      tags:
      - Survey Fields
      parameters:
      - name: filter[archived]
        in: query
        required: false
        schema:
          type: string
        description: "Filter by archived (â\x80\x98trueâ\x80\x99 or â\x80\x98falseâ\x80\
          \x99)"
      - name: filter[global]
        in: query
        required: false
        schema:
          type: string
        description: "Filter by global (â\x80\x98trueâ\x80\x99 or â\x80\x98falseâ\x80\
          \x99)"
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by name (string)
      - name: filter[origin_field_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by origin_field_id (string)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by project_id (string)
      - name: filter[survey_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by survey_id (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Creates a survey field POST
      operationId: postSurveyFields
      tags:
      - Survey Fields
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/survey_fields/{id}:
    get:
      summary: Gets a survey field GET
      operationId: getSurveyFieldsId
      tags:
      - Survey Fields
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Updates a survey field PATCH
      operationId: patchSurveyFieldsId
      tags:
      - Survey Fields
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/survey_fields/{id}/archive:
    patch:
      summary: Archives a survey field PATCH
      operationId: patchSurveyFieldsIdArchive
      tags:
      - Survey Fields
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
