openapi: 3.0.3
info:
  title: Productive.io API – Surveys
  version: 2.0.0
paths:
  /api/v2/surveys:
    get:
      summary: Get surveys GET
      operationId: getSurveys
      tags:
      - Surveys
      parameters:
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by created_at (string)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by creator_id (string)
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by project_id (string)
      - name: filter[title]
        in: query
        required: false
        schema:
          type: string
        description: Filter by title (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - id
          - title
          - -id
          - -title
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a survey POST
      operationId: postSurveys
      tags:
      - Surveys
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/surveys/{id}:
    get:
      summary: Gets a survey GET
      operationId: getSurveysId
      tags:
      - Surveys
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a survey PATCH
      operationId: patchSurveysId
      tags:
      - Surveys
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a survey DELETE
      operationId: deleteSurveysId
      tags:
      - Surveys
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/surveys/copy:
    post:
      summary: Copies a survey POST
      operationId: postSurveysCopy
      tags:
      - Surveys
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
