openapi: 3.0.3
info:
  title: Productive.io API – Tasks
  version: 2.0.0
paths:
  /api/v2/tasks:
    get:
      summary: Get tasks GET
      operationId: getTasks
      tags:
      - Tasks
      parameters:
      - name: filter[after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by after (string)
      - name: filter[assignee_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by assignee_id (array)
      - name: filter[before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by before (string)
      - name: filter[billable_time]
        in: query
        required: false
        schema:
          type: string
        description: Filter by billable_time (string)
      - name: filter[board_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by board_id (array)
      - name: filter[board_name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by board_name (string)
      - name: filter[board_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by board_status (1: active, 2: archived)'
      - name: filter[closed_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by closed_after (string)
      - name: filter[closed_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by closed_at (string)
      - name: filter[closed_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by closed_before (string)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by created_at (string)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by creator_id (array)
      - name: filter[custom_fields]
        in: query
        required: false
        schema:
          type: string
        description: Filter by custom_fields (string)
      - name: filter[date_range]
        in: query
        required: false
        schema:
          type: string
        description: Filter by date_range (string)
      - name: filter[dependency_type]
        in: query
        required: false
        schema:
          type: string
        description: Filter by dependency_type (string)
      - name: filter[description]
        in: query
        required: false
        schema:
          type: string
        description: Filter by description (string)
      - name: filter[due_date]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by due_date (1: any, 2: overdue)'
      - name: filter[due_date_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by due_date_after (string)
      - name: filter[due_date_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by due_date_before (string)
      - name: filter[due_date_on]
        in: query
        required: false
        schema:
          type: string
        description: Filter by due_date_on (string)
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[initial_estimate]
        in: query
        required: false
        schema:
          type: string
        description: Filter by initial_estimate (string)
      - name: filter[last_actor_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by last_actor_id (string)
      - name: filter[last_activity]
        in: query
        required: false
        schema:
          type: string
        description: Filter by last_activity (string)
      - name: filter[last_activity_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by last_activity_after (string)
      - name: filter[last_activity_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by last_activity_before (string)
      - name: filter[overdue_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by overdue_status (1: not overdue, 2: overdue)'
      - name: filter[parent_task_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by parent_task_id (array)
      - name: filter[person_type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by person_type (1: user, 2: contact, 3: placeholder)'
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[project_manager_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_manager_id (array)
      - name: filter[project_type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by project_type (1: internal project, 2 :client project)'
      - name: filter[public_access]
        in: query
        required: false
        schema:
          type: string
        description: Filter by public_access (string)
      - name: filter[query]
        in: query
        required: false
        schema:
          type: string
        description: Filter by query (string)
      - name: filter[remaining_time]
        in: query
        required: false
        schema:
          type: string
        description: Filter by remaining_time (string)
      - name: filter[repeating]
        in: query
        required: false
        schema:
          type: string
        description: Filter by repeating (string)
      - name: filter[start_date]
        in: query
        required: false
        schema:
          type: string
        description: Filter by start_date (string)
      - name: filter[start_date_after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by start_date_after (string)
      - name: filter[start_date_before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by start_date_before (string)
      - name: filter[status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by status (1: open, 2: closed)'
      - name: filter[subscriber_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by subscriber_id (array)
      - name: filter[tags]
        in: query
        required: false
        schema:
          type: string
        description: Filter by tags (string)
      - name: filter[task_list_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by task_list_id (array)
      - name: filter[task_list_name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by task_list_name (string)
      - name: filter[task_list_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by task_list_status (1: open, 2: closed)'
      - name: filter[task_number]
        in: query
        required: false
        schema:
          type: string
        description: Filter by task_number (string)
      - name: filter[task_type]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by task_type (1: parent task, 2: subtask)'
      - name: filter[title]
        in: query
        required: false
        schema:
          type: string
        description: Filter by title (string)
      - name: filter[updated_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by updated_at (string)
      - name: filter[worked_time]
        in: query
        required: false
        schema:
          type: string
        description: Filter by worked_time (string)
      - name: filter[workflow_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by workflow_id (array)
      - name: filter[workflow_status_category_id]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by workflow_status_category_id (1: not started, 2: started,
          3: closed)'
      - name: filter[workflow_status_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by workflow_status_id (array)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - assignee_name
          - billable_time
          - board_name
          - board_position
          - closed_at
          - company_name
          - created_at
          - creator_name
          - custom_fields
          - due_date - sorts due_date and then due_time
          - placement
          - id
          - initial_estimate
          - last_activity
          - last_activity_at
          - last_actor_name
          - number
          - project_name
          - remaining_time
          - start_date
          - task_list_name
          - task_list_position
          - task_number
          - title
          - updated_at
          - worked_time
          - workflow_status_name
          - workflow_status_position
          - -assignee_name
          - -billable_time
          - -board_name
          - -board_position
          - -closed_at
          - -company_name
          - -created_at
          - -creator_name
          - -custom_fields
          - -due_date - sorts due_date and then due_time
          - -placement
          - -id
          - -initial_estimate
          - -last_activity
          - -last_activity_at
          - -last_actor_name
          - -number
          - -project_name
          - -remaining_time
          - -start_date
          - -task_list_name
          - -task_list_position
          - -task_number
          - -title
          - -updated_at
          - -worked_time
          - -workflow_status_name
          - -workflow_status_position
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a task POST
      operationId: postTasks
      tags:
      - Tasks
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/tasks/{id}:
    get:
      summary: Gets a task GET
      operationId: getTasksId
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a task PATCH
      operationId: patchTasksId
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a task DELETE
      operationId: deleteTasksId
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/tasks/copy:
    post:
      summary: Copies a task POST
      operationId: postTasksCopy
      tags:
      - Tasks
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/tasks/{id}/reposition:
    patch:
      summary: Repositions a task PATCH
      operationId: patchTasksIdReposition
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
