openapi: 3.0.3
info:
  title: Productive.io API – Teams
  version: 2.0.0
paths:
  /api/v2/teams:
    get:
      summary: Get teams GET
      operationId: getTeams
      tags:
      - Teams
      parameters:
      - name: filter[color_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by color_id (string)
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        description: Filter by name (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - name
          - -name
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a team POST
      operationId: postTeams
      tags:
      - Teams
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/teams/{id}:
    get:
      summary: Gets a team GET
      operationId: getTeamsId
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a team PATCH
      operationId: patchTeamsId
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a team DELETE
      operationId: deleteTeamsId
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
