openapi: 3.0.3
info:
  title: Productive.io API – Timesheet Reports
  version: 2.0.0
paths:
  /api/v2/reports/timesheet_reports:
    get:
      summary: Get timesheet reports GET
      operationId: getReportsTimesheetReports
      tags:
      - Timesheet Reports
      parameters:
      - name: filter[person_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by person_id (array)
      - name: filter[tags]
        in: query
        required: false
        schema:
          type: string
        description: Filter by tags (string)
      - name: filter[after]
        in: query
        required: false
        schema:
          type: string
        description: Filter by after (string)
      - name: filter[before]
        in: query
        required: false
        schema:
          type: string
        description: Filter by before (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
