openapi: 3.0.3
info:
  title: Productive.io API – Time Entry Versions
  version: 2.0.0
paths:
  /api/v2/time_entry_versions:
    get:
      summary: Get time entry versions GET
      operationId: getTimeEntryVersions
      tags:
      - Time Entry Versions
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by creator_id (string)
      - name: filter[event]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by event ( create, update, destroy, restore)
      - name: filter[created_at]
        in: query
        required: false
        schema:
          type: string
        description: Filter by created_at (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/time_entry_versions/{id}:
    get:
      summary: Gets a time entry version GET
      operationId: getTimeEntryVersionsId
      tags:
      - Time Entry Versions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
