openapi: 3.0.3
info:
  title: Productive.io API – Timesheets
  version: 2.0.0
paths:
  /api/v2/timesheets:
    get:
      summary: Get timesheets GET
      operationId: getTimesheets
      tags:
      - Timesheets
      parameters:
      - name: filter[date]
        in: query
        required: false
        schema:
          type: string
        description: Filter by date (string)
      - name: filter[person_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by person_id (array)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by creator_id (array)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - id
          - date
          - person_id
          - -id
          - -date
          - -person_id
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/timesheets/{id}:
    get:
      summary: Gets a timesheet GET
      operationId: getTimesheetsId
      tags:
      - Timesheets
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    delete:
      summary: Deletes a timesheet DELETE
      operationId: deleteTimesheetsId
      tags:
      - Timesheets
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
