openapi: 3.0.3
info:
  title: Productive.io API – Time Entries
  version: 2.0.0
paths:
  /api/v2/time_entries:
    get:
      summary: Get time entries GET
      operationId: getTimeEntries
      tags:
      - Time Entries
      parameters:
      - name: filter[after]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by after (date)
      - name: filter[approved_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by approved_at (date)
      - name: filter[approver_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by approver_id (array)
      - name: filter[autotracked]
        in: query
        required: false
        schema:
          type: string
        description: Filter by autotracked (string)
      - name: filter[before]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by before (date)
      - name: filter[billing_type_id]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by billing_type_id (1: fixed, 2: actuals, 3: non_billable)'
      - name: filter[booking_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by booking_id (array)
      - name: filter[budget_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by budget_id (array)
      - name: filter[company_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by company_id (array)
      - name: filter[creator_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by creator_id (array)
      - name: filter[date]
        in: query
        required: false
        schema:
          type: string
        description: Filter by date (string)
      - name: filter[deal_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by deal_id (array)
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[invoicing_status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by invoicing_status (1: not_invoiced, 2: drafted, 3:
          finalized)'
      - name: filter[invoice_attribution_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by invoice_attribution_id (array)
      - name: filter[invoice_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by invoice_id (array)
      - name: filter[invoiced]
        in: query
        required: false
        schema:
          type: boolean
        description: Filter by invoiced (boolean)
      - name: filter[jira_issue_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by jira_issue_id (string)
      - name: filter[jira_issue_status]
        in: query
        required: false
        schema:
          type: string
        description: Filter by jira_issue_status (string)
      - name: filter[jira_issue_summary]
        in: query
        required: false
        schema:
          type: string
        description: Filter by jira_issue_summary (string)
      - name: filter[jira_worklog_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by jira_worklog_id (string)
      - name: filter[last_activity_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by last_activity_at (date)
      - name: filter[last_actor_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by last_actor_id (array)
      - name: filter[person_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by person_id (array)
      - name: filter[project_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by project_id (array)
      - name: filter[responsible_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by responsible_id (array)
      - name: filter[service_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by service_id (array)
      - name: filter[started_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by started_at (date)
      - name: filter[status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by status (1: approved, 2: unapproved, 3: rejected)'
      - name: filter[status]
        in: query
        required: false
        schema:
          type: string
        description: Filter by status (string)
      - name: filter[task_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by task_id (array)
      - name: filter[time]
        in: query
        required: false
        schema:
          type: integer
        description: Filter by time (integer)
      - name: filter[track_method_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by track_method_id (array)
      - name: filter[updated_at]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by updated_at (date)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      - name: sort
        in: query
        required: false
        schema:
          type: string
          enum:
          - date
          - updated_at
          - jira_issue_id
          - jira_issue_status
          - jira_issue_summary
          - -date
          - -updated_at
          - -jira_issue_id
          - -jira_issue_status
          - -jira_issue_summary
        description: Sort field. Prefix - for descending.
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
  /api/v2/time_entries/{id}:
    get:
      summary: Gets a time entry GET
      operationId: getTimeEntriesId
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a time entry PATCH
      operationId: patchTimeEntriesId
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a time entry DELETE
      operationId: deleteTimeEntriesId
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/time_entries/{id}/approve:
    patch:
      summary: Approves a time entry PATCH
      operationId: patchTimeEntriesIdApprove
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/time_entries/{id}/unapprove:
    patch:
      summary: Unapproves a time entry PATCH
      operationId: patchTimeEntriesIdUnapprove
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/time_entries/{id}/reject:
    patch:
      summary: Reject a time entry PATCH
      operationId: patchTimeEntriesIdReject
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/time_entries/{id}/unreject:
    patch:
      summary: Unreject a time entry PATCH
      operationId: patchTimeEntriesIdUnreject
      tags:
      - Time Entries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
