openapi: 3.0.3
info:
  title: Productive.io API – Time Entries   Bulk
  version: 2.0.0
paths:
  /api/v2/time_entries:
    post:
      summary: Create time entries POST
      operationId: postTimeEntries
      tags:
      - Time Entries   Bulk
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    patch:
      summary: Update time entries PATCH
      operationId: patchTimeEntries
      tags:
      - Time Entries   Bulk
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes time entries DELETE
      operationId: deleteTimeEntries
      tags:
      - Time Entries   Bulk
      parameters: []
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
  /api/v2/time_entries/approve:
    patch:
      summary: Approves time entries PATCH
      operationId: patchTimeEntriesApprove
      tags:
      - Time Entries   Bulk
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/time_entries/unapprove:
    patch:
      summary: Unapproves time entries PATCH
      operationId: patchTimeEntriesUnapprove
      tags:
      - Time Entries   Bulk
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
