openapi: 3.0.3
info:
  title: Productive.io API – Todos
  version: 2.0.0
paths:
  /api/v2/todos:
    get:
      summary: Get todos GET
      operationId: getTodos
      tags:
      - Todos
      parameters:
      - name: filter[deal_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by deal_id (array)
      - name: filter[task_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by task_id (array)
      - name: filter[assignee_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by assignee_id (array)
      - name: filter[status]
        in: query
        required: false
        schema:
          type: string
        description: 'Filter by status (1: open, 2: closed)'
      - name: filter[due_date]
        in: query
        required: false
        schema:
          type: string
        description: Filter by due_date (string)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    post:
      summary: Create a todo POST
      operationId: postTodos
      tags:
      - Todos
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
  /api/v2/todos/{id}:
    get:
      summary: Gets a todo GET
      operationId: getTodosId
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
    patch:
      summary: Update a todo PATCH
      operationId: patchTodosId
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                    relationships:
                      type: object
    delete:
      summary: Deletes a todo DELETE
      operationId: deleteTodosId
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: id of the resource
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
