openapi: 3.0.3
info:
  title: Productive.io API – Webhook Logs
  version: 2.0.0
paths:
  /api/v2/webhook_logs:
    get:
      summary: Get webhook logs GET
      operationId: getWebhookLogs
      tags:
      - Webhook Logs
      parameters:
      - name: filter[id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by id (string)
      - name: filter[webhook_id]
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: Filter by webhook_id (array)
      - name: filter[retry_attempt]
        in: query
        required: false
        schema:
          type: string
        description: Filter by retry_attempt (string)
      - name: filter[retry_job_id]
        in: query
        required: false
        schema:
          type: string
        description: Filter by retry_job_id (string)
      - name: filter[before]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by before (date)
      - name: filter[after]
        in: query
        required: false
        schema:
          type: string
          format: date
        description: Filter by after (date)
      - name: page[number]
        in: query
        required: false
        schema:
          type: integer
          default: 1
      - name: page[size]
        in: query
        required: false
        schema:
          type: integer
          default: 30
          maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data: {}
                  meta:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Validation error
